FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# ЗАКОММЕНТИРУЕМ СБОРКУ TYPESCRIPT - ЗАПУСКАЕМ ЧЕРЕЗ TSX
# RUN npm run build

EXPOSE 3007

CMD ["npm", "run", "dev"]